bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.urls import path
from django.contrib.auth.views import *
from django.urls import reverse_lazy
from django.core.mail import EmailMessage

from .views import index, by_rubric, add_rub, add_and_save, BbDetailView, BbEditView, CarEditView, BbDeleteView, \
    profile_view, \
    by_logged_user, update_profile, profile_ads_view, user_reg, search_ads, BbCreateView, CarDetailView, \
    add_car_by_brand

urlpatterns = [
    path('add/', add_rub, name='add'),
    path('add_<int:rubric_id>/', add_and_save, name='add_by_rub'),
    path('add_<int:rubric_id>_<int:carbrand_id>/', add_car_by_brand, name='add_car_by_brand'),
    path('detail/<int:pk>/', BbDetailView.as_view(), name='detail'),
    path('detail_car/<int:pk>/', CarDetailView.as_view(), name='detail_car'),
    path('car_edit/<int:pk>/', CarEditView.as_view(), name='car_edit'),
    path('edit/<int:pk>/', BbEditView.as_view(), name='edit'),
    path('delete/<int:pk>/', BbDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>/uinfo/', profile_ads_view, name='profile_ads_view'),
    path('<int:rubric_id>/', by_rubric, name='by_rubric'),
    path('', index, name='index'),
    path('search/', search_ads, name='search_ads'),
    path('accounts/registrate/', user_reg, name='user_registrate'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('accounts/profile/', profile_view, name='profile'),
    path('accounts/profile/update/', update_profile, name='update_profile'),
    path('accounts/profile/ads/', by_logged_user, name='by_logged_user'),
    path('accounts/password_change/',  # смена пароля
         PasswordChangeView.as_view(
             template_name='registration/change_password.html'),
         name='password_change'),
    path('accounts/password_change/done/',  # уведомление об успешной смене пароля
         PasswordChangeDoneView.as_view(
             template_name='registration/password_changed.html'),
         name='password_change_done'),
    path('accounts/password_reset/',  # отправка пиьсма для сброса пароля
         PasswordResetView.as_view(
             template_name='registration/reset_password.html',
             subject_template_name='registration/reset_subject.txt',
             email_template_name='registration/reset_email.txt'),
         name='password_reset'),
    path('accounts/password_reset/done/',  # уведомление об отправке письма для сброса паролдя
         PasswordResetDoneView.as_view(
             template_name='registration/email_sent.html'),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',  # сброс пароля
         PasswordResetConfirmView.as_view(
             template_name='registration/confirm_password.html'),
         name='password_reset_confirm'),
    path('accounts/reset/done/',  # уведомление об успешном сбросе пароля
         PasswordResetCompleteView.as_view(
             template_name='registration/password_confirmed.html'),
         name='password_reset_complete'),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(unique=True, max_length=16, null=True, blank=True, verbose_name='Номер телефона')
    birth_date = models.DateField(null=True, blank=True, verbose_name='День рождения')


User.profile = property(lambda u: Profile.objects.get_or_create(user=u)[0])


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Bb(models.Model):
    title = models.CharField(max_length=50, verbose_name='Товар',
                             validators=[validators.MinLengthValidator(3,
                                                                       message='Название должно быть от 3 символов')])
    content = models.TextField(null=True, blank=True, verbose_name='Описание',
                               validators=[validators.MinLengthValidator(5,
                                                                         message='Описание должно быть от 5 символов')])
    price = models.FloatField(null=True, blank=True, verbose_name='Цена')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')
    rubric = models.ForeignKey('Rubric', null=True, on_delete=models.PROTECT,
                               verbose_name='Рубрика')
    buser = models.CharField(max_length=20, null=True, blank=True, verbose_name='Пользователь')

    class Meta:
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['-published']

    class Kinds(models.TextChoices):
        BUY = 'b', 'Куплю'
        SELL = 's', 'Продам'
        EXCHANGE = 'c', 'Обменяю'
        RENT = 'r', 'Сдам в аренду'

    kind = models.CharField(max_length=1, choices=Kinds.choices, default=Kinds.SELL, verbose_name='Тип')

    def clean(self):
        errors = {}
        if not self.content:
            errors['content'] = ValidationError('Заполните описание')
        if self.price and self.price < 0:
            errors['price'] = ValidationError('Цена не может быть отрицательной!')
        if errors:
            raise ValidationError(errors)

    def user_dir(instance, filename):
        return '{0}/images/{1}'.format(instance.buser, filename)

    photo = models.ImageField(upload_to=user_dir, null=True, blank=True, verbose_name='Фото')


class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['name']


class AdvUser(models.Model):
    is_activated = models.BooleanField(default=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)


class CarBrands(models.Model):
    class CarBrand(models.TextChoices):
        AUDI = 'Audi', 'Audi'
        BMW = 'BMW', 'BMW'
        CHERY = 'Chery', 'Chery'
        CHEVROLET = 'Chevrolet', 'Chevrolet'
        CITROEN = 'Citroen', 'Citroen'
        DAEWOO = 'Daewoo', 'Daewoo'
        FORD = 'Ford', 'Ford'
        GAZ = 'Газ', 'Газ'
        GEELY = 'Geely', 'Geely'
        HAVAL = 'Haval', 'Haval'
        HONDA = 'Honda', 'Honda'
        HYUNDAI = 'Hyundai', 'Hyundai'
        INFINITI = 'Infiniti', 'Infiniti'
        KIA = 'KIA', 'KIA'
        LADA = 'Lada', 'Lada'
        LANDROVER = 'Land Rover', 'Land Rover'
        LEXUS = 'Lexus', 'Lexus'
        MINI = 'Mini', 'Mini'
        MAZDA = 'Mazda', 'Mazda'
        MERCEDES = 'Mercedes-Benz', 'Mercedes-Benz'
        NISSAN = 'Nissan', 'Nissan'
        OPEL = 'Opel', 'Opel'
        PORSCHE = 'Porsche', 'Porsche'
        RENAULT = 'Renault', 'Renault'
        SKODA = 'Skoda', 'Skoda'
        SUZUKI = 'Suzuki', 'Suzuki'
        TOYOTA = 'Toyota', 'Toyota'
        VOLKSWAGEN = 'Volkswagen', 'Volkswagen'
        VOLVO = 'Volvo', 'Volvo'
        __empty__ = 'Выберите марку машины'

    name = models.CharField(max_length=20, db_index=True, choices=CarBrand.choices, verbose_name='Марка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Марки авто'
        verbose_name = 'Марка авто'
        ordering = ['name']


class CarModels(models.Model):
    name = models.CharField(max_length=20, null=True, verbose_name='Модель')
    brand = models.ForeignKey('CarBrands', db_index=True, null=True, on_delete=models.CASCADE, verbose_name='Марка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Модели авто'
        verbose_name = 'Модель авто'
        ordering = ['name']


class Car(Bb):
    mileage = models.IntegerField(null=True, blank=True, verbose_name='Пробег')
    year = models.IntegerField(null=False, default='2020', verbose_name='Год выпуска')
    model = models.ForeignKey('CarModels', null=True, on_delete=models.PROTECT, verbose_name='Модель')
    is_competitive = models.IntegerField(default=0, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Авто объявления'
        verbose_name = 'Авто объявление'
        ordering = ['-published']

    class CarBody(models.IntegerChoices):
        SEDAN = 1, 'Седан'
        COUPE = 2, 'Купе'
        HATCHBACK3 = 3, 'Хэтчбек 3 дв.'
        HATCHBACK5 = 4, 'Хэтчбек 5 дв.'
        OFFROAD3 = 5, 'Внедорожник 3 дв.'
        OFFROAD5 = 6, 'Внедорожник 5 дв.'
        LIFTBACK = 7, 'Лифтбек'
        CABRIOLET = 8, 'Кабриолет'
        UNIVERSAL = 9, 'Универсал'
        LIMO = 10, 'Лимузин'

    body = models.PositiveSmallIntegerField(choices=CarBody.choices, default=CarBody.SEDAN, verbose_name='Тип кузова')

    class EngineType(models.TextChoices):
        BENZIN = 'b', 'Бензин'
        DIESEL = 'd', 'Дизель'
        ELECTRO = 'e', 'Электро'
        HIBRID = 'h', 'Гибрид'
        GAS = 'g', 'Газ'

    engine_type = models.CharField(max_length=1, choices=EngineType.choices, default=EngineType.BENZIN,
                                   verbose_name='Тип двигателя')

    class GearShift(models.TextChoices):
        ROBOT = 'r', 'Роботизированная'
        CLASSICAUTO = 'a', 'Автоматическая'
        VARIATOR = 'v', 'Вариатор'
        MANUAL = 'm', 'Механическая'

    gear = models.CharField(max_length=1, choices=GearShift.choices, default=GearShift.MANUAL,
                            verbose_name='Коробка передач')

    class WheelDrive(models.IntegerChoices):
        FRONT = 1, 'Передний'
        REAR = 2, 'Задний'
        FULL = 3, 'Полный'

    drive = models.PositiveSmallIntegerField(choices=WheelDrive.choices, default=WheelDrive.FRONT,
                                             verbose_name='Тип привода')

    class CarStatus(models.TextChoices):
        NEW = 'n', 'Новая'
        USED = 'u', 'С пробегом'

    status = models.CharField(max_length=1, choices=CarStatus.choices, default=CarStatus.USED, verbose_name='Состояние')

    class CarEquipment(models.TextChoices):
        HIGH = 'h', 'Максимальная'
        MIDDLE = 'm', 'Средняя'
        START = 's', 'Базовая'

    equip = models.CharField(max_length=1, choices=CarEquipment.choices, default=CarEquipment.START,
                             verbose_name='Комплектация')

    class CarColor(models.IntegerChoices):
        RED = 1, 'Красный'
        GREEN = 2, 'Зеленый'
        BLUE = 3, 'Синий'
        WHITE = 4, 'Белый'
        BLACK = 5, 'Черный'
        YELLOW = 6, 'Желтый'
        LIGTH_BLUE = 7, 'Голубой'
        ORANGE = 8, 'Оранжевый'
        PINK = 9, 'Розовый'
        BROWN = 10, 'Коричневый'
        GREY = 11, 'Серый'
        VINOUS = 12, 'Бордовый'
        BEIGE = 13, 'Бежевый'
        GOLDEN = 14, 'Золотой'

    color = models.PositiveSmallIntegerField(choices=CarColor.choices, default=CarColor.WHITE, verbose_name='Цвет')

    class CarPts(models.IntegerChoices):
        ORIGINAL = 1, 'Оригинал'
        DUBLICATE = 2, 'Дубликат'

    pts = models.PositiveSmallIntegerField(choices=CarPts.choices, default=CarPts.ORIGINAL, verbose_name='ПТС')

    class CarOwners(models.IntegerChoices):
        ONE = 1, 'Один'
        TWO = 2, 'Два'
        MORE = 3, 'Три и более'
        NEW = 4, 'Новый авто'

    owners = models.PositiveSmallIntegerField(choices=CarOwners.choices, default=CarOwners.ONE,
                                              verbose_name='Собственников в ПТС')


class Message(models.Model):
    content = models.TextField()
    name = models.CharField(max_length=20)
    email = models.EmailField()

    class Meta:
        abstract = True


class PrivateMessage(Message):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    email = None

bboard/forms.py
from django.conf import settings
from django.forms import ModelForm, DecimalField
from django import forms
from django.forms.widgets import Select

from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from datetime import date

from .models import Bb, Rubric, Profile, Car, CarBrands, CarModels


class StartForm(ModelForm):
    rubric = forms.ModelChoiceField(queryset=Rubric.objects.all(), label='Рубрика', help_text='Выберите рубрику.',
                                    widget=forms.widgets.Select(attrs={'size': 8}))

    class Meta:
        model = Rubric
        fields = ('rubric',)


class BbForm(ModelForm):
    price = forms.DecimalField(label='Цена', decimal_places=2)
    photo = forms.ImageField(label='Фото', required=False)

    class Meta:
        model = Bb
        fields = ('title', 'kind', 'photo', 'content', 'price')

    def clean_title(self):
        val = self.cleaned_data['title']
        if val == 'Человек':
            raise ValidationError('Работорговля запрещена!')
        return val


class CarBrandsForm(ModelForm):
    name = forms.ModelChoiceField(queryset=CarBrands.objects.all(), label='Марки', help_text='Выберите марку.',
                                  widget=forms.widgets.Select(attrs={'size': 8}))

    class Meta:
        model = CarBrands
        fields = ('name',)


class CarModelsForm(ModelForm):
    model = forms.ModelChoiceField(queryset=CarModels.objects.all(), label='Модель', help_text='Выберите модель.',
                                   widget=forms.widgets.Select(attrs={'size': 8}))

    class Meta:
        model = CarBrands
        fields = ('model',)


class CarForm(ModelForm):
    title = forms.CharField(label='Название авто')
    price = forms.DecimalField(label='Цена', decimal_places=2)
    photo = forms.ImageField(label='Фото', required=False)
    model = forms.ModelChoiceField(queryset=CarModels.objects.all(), label='Модель', help_text='Выберите модель.',
                                   widget=forms.widgets.Select(attrs={'size': 8}))

    class Meta:
        model = Car
        fields = ('title', 'kind', 'model', 'year', 'pts', 'owners', 'body', 'engine_type', 'drive', 'mileage',
                  'equip', 'status', 'color', 'photo', 'content', 'price')

    def clean_title(self):
        val = self.cleaned_data['title']
        if val == 'Человек':
            raise ValidationError('Работорговля запрещена!')
        return val

    def clean_year(self):
        val = self.cleaned_data['year']
        current_date = date.today()
        print(current_date)
        if (int(val) < int('1900')) or (int(val) > current_date.year):
            raise ValidationError('Дата выпуска введена неверно!')
        return val

    def __init__(self, carbrand_id, *args, **kwargs):
        super(CarForm, self).__init__(*args, **kwargs)
        self.fields['model'].queryset = CarModels.objects.filter(brand=carbrand_id)


class CarFormEdit(ModelForm):
    title = forms.CharField(label='Название авто')
    price = forms.DecimalField(label='Цена', decimal_places=2)
    photo = forms.ImageField(label='Фото', required=False)

    class Meta:
        model = Car
        fields = ('title', 'kind', 'model', 'year', 'pts', 'owners', 'body', 'engine_type', 'drive', 'mileage',
                  'equip', 'status', 'color', 'photo', 'content', 'price')

    def clean_title(self):
        val = self.cleaned_data['title']
        if val == 'Человек':
            raise ValidationError('Работорговля запрещена!')
        return val

    def clean_year(self):
        val = self.cleaned_data['year']
        current_date = date.today()
        print(current_date)
        if (int(val) < int('1900')) or (int(val) > current_date.year):
            raise ValidationError('Дата выпуска введена неверно!')
        return val


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileForm(ModelForm):
    birth_date = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS, label='День рождения')

    class Meta:
        model = Profile
        fields = ('phone_number', 'birth_date')

bboard/templates/bboard/bb_confirm_delete.html
{% extends "layout/basic.html" %}

{% block title %}Удаление объявления{% endblock %}

{% block content %}
<h2>Удаление объявления</h2>
<p>Рубрика: {{ bb.rubric.name }}</p>
<p>Товар: {{ bb.title }}</p>
<p>{{ bb.content }}</p>
<p>Цена: <b>{{ bb.price|default:'Продавец не указал цену' }}</b></p>
<form method="POST">
    {% csrf_token %}
    <h3><p>Точно хотите удалить объявление?</p></h3>
    <input type="submit" value="Удалить">
</form>
{% endblock %}

bboard/templates/bboard/bb_detail.html
{% extends "layout/basic.html" %}
{% load static %}

{% block title %}{{ bb.title }}{% endblock %}
{% block content %}
<p>Рубрика: {{ bb.rubric.name }}</p>
<h2>{{ bb.title }}</h2>
{% if bb.photo %}
<img src="{{ bb.photo.url }}" width="400px">
{% else %}
<p>Фотография отсутствует.</p>
{% endif %}
<p><br></p>
<p>{{ bb.content }}</p>
<p><br><br></p>
<p>Цена: <b>{{ bb.price|default:'Продавец не указал цену' }}</b> руб.</p>
{% if bb.buser %}
<p>Разместил: <a href="{% url 'profile_ads_view' pk=bb.pk %}">{{ bb.buser }}</a></p>
{% else %}
<p>Разместил: Администратор</p>
{% endif %}
<p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
{% if user.is_authenticated %}
{% if bb.buser == user.username %}
<p><a href="{% url 'edit' pk=bb.pk %}">Изменить объявление</a></p>
<p><a href="{% url 'delete' pk=bb.pk %}">Удалить объявление</a></p>
{% else %}
{% if 'bboard.add_bb' in perms %}
<p><a href="{% url 'edit' pk=bb.pk %}">Изменить объявление</a></p>
{% endif %}
{% if 'bboard.del_bb' in perms %}
<p><a href="{% url 'delete' pk=bb.pk %}">Удалить объявление</a></p>
{% endif %}
{% endif %}
{% endif %}
{% endblock %}
    

bboard/templates/bboard/bb_edit.html
{% extends "layout/basic.html" %}

{% block title %}Исправление объявления{% endblock %}

{% block content %}
<h2>Исправление объявления</h2>
<form enctype=multipart/form-data method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить">
</form>
{% endblock %}

bboard/templates/bboard/by_logged_user.html
{% extends "layout/basic.html" %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
<h2>Объявления: {{ user.username }}</h2>
{% for bb in bbs %}
{% if bb.buser == user.username %}
<div>
    {% if bb.rubric.name == 'Авто' %}
    <h2><a href="{% url 'detail_car' pk=bb.pk %}">{{ bb.title }}</a></h2>
    {% else %}
    <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    {% endif %}
    <p>{{ bb.content }}</p>
    <b><p>{{ bb.price }} руб.</p></b>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endif %}
{% endfor %}
{% endblock %}
    

bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>
{% for bb in bbs %}
<div>
    {% if current_rubric.name == 'Авто' %}
    <h2><a href="{% url 'detail_car' pk=bb.pk %}">{{ bb.title }}</a></h2>
    {% else %}
    <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    {% endif %}
    <p>{{ bb.content }}</p>
    <b><p>{{ bb.price }} руб.</p></b>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
{% endblock %}
    

bboard/templates/bboard/car_detail.html
{% extends "layout/basic.html" %}
{% load static %}

{% block title %}{{ car.title }}{% endblock %}
{% block content %}
<p>Рубрика: {{ car.rubric.name }}</p>
<h2>{{ car.title }}</h2>
<h3>{{ car.price|default:'Продавец не указал цену' }} ₽</h3>
{% with c=car.is_competitive %}
{% if c == 1 %}
<p><b style="background-color:#ADFF2F">Хорошая цена</b></p>
{% elif c == 2 %}
<p><b style="background-color:#00FF00">Отличная цена</p></b>
{% elif c == -1 %}
<p><b style="background-color:#B0E0E6">Цена слегка выше рынка</p></b>
{% elif c == -2 %}
<p><b style="background-color:#87CEEB">Цена существенно выше рынка</p></b>
{% else %}
{% endif %}
{% endwith %}
{% if car.photo %}
<p><img src="{{ car.photo.url }}" width="400px"></p>
{% else %}
<p>Фотография отсутствует.</p>
{% endif %}

<p>Тип объявления: <b>{{ car.get_kind_display }}</b></p>
<p>Состояние: {{ car.get_status_display }}</p>
<p>Марка: {{ car.model.brand }}</p>
<p>Модель: {{ car.model }}</p>
<p>Год выпуска: {{ car.year }}</p>
<p>Пробег: {{ car.mileage }} км.</p>
<p>ПТС: {{ car.get_pts_display }}</p>
<p>Собственников в ПТС: {{ car.get_owners_display }}</p>
<p>Тип кузова: {{ car.get_body_display }}</p>
<p>Цвет авто: {{ car.get_color_display }}</p>
<p>Тип двигателя: {{ car.get_engine_type_display }}</p>
<p>Привод: {{ car.get_drive_display }}</p>
<p>Комплектация: {{ car.get_equip_display }}</p>
<p><br></p>
<p><b>Описание</b></p>
<p>{{ car.content }}</p>
<p><br></p>
<p>Цена: <b>{{ car.price|default:'Продавец не указал цену' }}</b> руб.</p>
{% if car.buser %}
<p>Разместил: <a href="{% url 'profile_ads_view' pk=car.pk %}">{{ car.buser }}</a></p>
{% else %}
<p>Разместил: Администратор</p>
{% endif %}
<p>{{ car.published|date:"d.m.Y H:i:s" }}</p>
{% if user.is_authenticated %}
{% if car.buser == user.username %}
<p><a href="{% url 'car_edit' pk=car.pk %}">Изменить объявление</a></p>
<p><a href="{% url 'delete' pk=car.pk %}">Удалить объявление</a></p>
{% else %}
{% if 'bboard.add_bb' in perms %}
<p><a href="{% url 'car_edit' pk=car.pk %}">Изменить объявление</a></p>
{% endif %}
{% if 'bboard.del_bb' in perms %}
<p><a href="{% url 'delete' pk=car.pk %}">Удалить объявление</a></p>
{% endif %}
{% endif %}
{% endif %}
{% endblock %}
    

bboard/templates/bboard/create.html
{% extends "layout/basic.html" %}

{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>
<h2>в рубрику "{{ current_rubric.name }}"</h2>
{% if user.is_authenticated %}
<form enctype=multipart/form-data method="POST">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% if form.non_field_errors %}
    <ul>
        {% for error in form.non_field_errors %}
        <li><em>{{ error|escape }}</em></li>
        {% endfor %}
    </ul>
    {% endif %}
    {% for field in form.visible_fields %}
    {% if field.errors %}
    <ul>
        {% for error in field.errors %}
        <li><em>{{ error|escape }}</em></li>
        {% endfor %}
    </ul>
    {% endif %}
    <p>{{ field.label_tag }}<br>{{ field }}<br>{{ field.help_text }}</p>
    {% endfor %}
    <p><input type="submit" value="Добавить"></p>
</form>
{% else %}
<p>Вы не авторизованы!</p>
{% endif %}
{% endblock %}

bboard/templates/bboard/create_rub.html
{% extends "layout/basic.html" %}

{% block title %}Добавление объявления{% endblock %}

{% block content %}
<h2>Добавление объявления</h2>
{% if user.is_authenticated %}
<form enctype=multipart/form-data method="GET">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% if form.non_field_errors %}
    <ul>
        {% for error in form.non_field_errors %}
        <li><em>{{ error|escape }}</em></li>
        {% endfor %}
    </ul>
    {% endif %}
    {% for field in form.visible_fields %}
    {% if field.errors %}
    <ul>
        {% for error in field.errors %}
        <li><em>{{ error|escape }}</em></li>
        {% endfor %}
    </ul>
    {% endif %}
    <p>{{ field.label_tag }}<br>{{ field }}<br>{{ field.help_text }}</p>
    {% endfor %}
    <p><input type="submit" value="Выбрать"></p>
</form>
{% else %}
<p>Вы не авторизованы!</p>
{% endif %}
{% endblock %}

bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}

{% block content %}

{% if bbs %}
{% for bb in bbs %}
<div>
    {% if bb.rubric.name == 'Авто' %}
    <h2><a href="{% url 'detail_car' pk=bb.pk %}">{{ bb.title }}</a></h2>
    {% else %}
    <h2><a href="{% url 'detail' pk=bb.pk %}">{{ bb.title }}</a></h2>
    {% endif %}
    <p><a href="{% url 'by_rubric' bb.rubric.pk %}">{{ bb.rubric.name }}</a></p>
    <p>{{ bb.content }}</p>
    <b><p>{{ bb.price }} руб.</p></b>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>


</div>
{% endfor %}
<div>

    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">&lt;</a>
    &nbsp;&nbsp;|&nbsp;&nbsp;
    {% endif %}

    Часть №{{ page.number }} из {{ page.paginator.num_pages }}

    {% if page.has_next %}
    &nbsp;&nbsp;|&nbsp;&nbsp;
    <a href="?page={{ page.next_page_number }}">&gt;</a>
    {% endif %}
</div>

{% else %}
<p>Тут пока еще нет объявлений.</p>
{% endif %}

{% endblock %}